### ISSUE TITLE
FAQ list overflows depending on resolution

### ISSUE THREAD

**Issue by MechanicalDragon0687** [nh-server/switch-guide#8]
FAQ list on the left overflows the page depending on screen resolution. unable to see the last few options.
![image](https://user-images.githubusercontent.com/43786828/51920333-0ce85800-239a-11e9-9d0f-92293155c93b.png)

**Comment by Flumpster** [comment]
Should be fixed. Tested it in 1024*768 and works.

**Comment by thecogdoctor** [comment]
Still experiencing this phenomenon in 1920x1080.

**Comment by Flumpster** [comment]
1920x1080
[https://flumpster.lolcakes.com/forums/1920.png](url)

1024x768
[https://flumpster.lolcakes.com/forums/1024.png](url)

**Comment by NovaPhoenix** [comment]
@thecogdoctor what browser are you using?

**Comment by MechanicalDragon0687** [comment]
fixed on my end too

**Comment by thecogdoctor** [comment]
@NovaPhoenix Firefox

**Comment by NovaPhoenix** [comment]
Unfortunately I don't think that there's much we can do here for lower resolutions, as the problem seems to reside in the mkdocs framework. But the fact that it's still happening at 1080p is very odd, @thecogdoctor could you please share some screenshots and more information about what operating system/resolution that you're using?

**Comment by thecogdoctor** [comment]
Windows 10, I will edit this post to include the resolution asap.
I feel like a few sections titles should be reduced vastly reduced in length or sections separated etc. This will likely be the best way ensure this bug is resolved.

**Comment by NovaPhoenix** [comment]
@thecogdoctor like I asked, could you please share a screenshot?
